### ISSUE TITLE
get_primary

### ISSUE THREAD

**Issue by eilifso** [ITA-Solar/BifrostTools.jl#2]
Implement `get_primary` - the fastest way to load primary variables. From a single or multiple snapshots, and optionally sliced snapshots.

**Comment by tiagopereira** [comment]
I'm not sure if I agree with specific methods for different types of variables. The user does not necessarily know what a primary variable is. This is also less flexible if you want to have the same interface for other codes.

**Comment by eilifso** [comment]
Good point. We should keep the implementations of the `get_var`-methods. But if a `get_primary` function proves to be faster I think we should consider adding this too. Alternatively adding it through a "fast-primary-load" `get_var`-method.

**Comment by eilifso** [comment]
Does not seem to be significantly faster.
